# Generated by Django 5.2.6 on 2025-09-26 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
